#pragma once
#define TILE_SIZE 32 

#define SCREEN_WIDTH    TILE_SIZE*30
#define SCREEN_HEIDHT    TILE_SIZE*18
#define MAP_WIDTH     SCREEN_WIDTH*3
#define MAP_HEIDTH SCREEN_HEIDHT*1.5
#define LIMIT_FPS 60

#define PLAYER_SPEED_DEFAULT 144
#define enemy_speed 0.8

#define GRAVITY PLAYER_SPEED_DEFAULT*10
#define STAMINA 10000
#define HP_DEFAULT 100
