#pragma once
#define TILE_SIZE 96 

#define SCREEN_WIDTH    TILE_SIZE*10
#define SCREEN_HEIDHT    TILE_SIZE*6
#define MAP_WIDTH     SCREEN_WIDTH*3
#define MAP_HEIDTH SCREEN_HEIDHT*1.5
#define LIMIT_FPS 60

#define PLAYER_SPEED_DEFAULT 144

#define GRAVITY PLAYER_SPEED_DEFAULT*10
#define STAMINA 100
#define HP_DEFAULT 100
